/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.g1.android.puzzle;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int button_color=0x7f050000;
        public static final int text_color=0x7f050001;
    }
    public static final class drawable {
        public static final int aum=0x7f020000;
        public static final int npicon=0x7f020001;
    }
    public static final class id {
        public static final int Button0=0x7f060003;
        public static final int Button1=0x7f060004;
        public static final int Button10=0x7f06000f;
        public static final int Button11=0x7f060010;
        public static final int Button12=0x7f060012;
        public static final int Button13=0x7f060013;
        public static final int Button14=0x7f060014;
        public static final int Button15=0x7f060015;
        public static final int Button2=0x7f060005;
        public static final int Button3=0x7f060006;
        public static final int Button4=0x7f060008;
        public static final int Button5=0x7f060009;
        public static final int Button6=0x7f06000a;
        public static final int Button7=0x7f06000b;
        public static final int Button8=0x7f06000d;
        public static final int Button9=0x7f06000e;
        public static final int ImageView01=0x7f060000;
        public static final int Row1=0x7f060002;
        public static final int Row2=0x7f060007;
        public static final int Row3=0x7f06000c;
        public static final int Row4=0x7f060011;
        public static final int Table=0x7f060001;
    }
    public static final class layout {
        public static final int image=0x7f030000;
        public static final int npuzzle=0x7f030001;
    }
    public static final class string {
        public static final int about_content=0x7f040003;
        public static final int about_title=0x7f040002;
        public static final int app_name=0x7f040000;
        public static final int restart=0x7f040001;
        public static final int win_text=0x7f040004;
        public static final int win_title=0x7f040005;
    }
}
